import React from 'react';
import { Link } from 'react-router-dom';
import './NHI.css';
import Volvox from '../assets/Volvox-QR-Code-V3.png'
import NCW from '../assets/Ni6W6C-Viewer.png'
import ArcMain from '../assets/Arc-Main.png'
import ChineseIron from '../assets/Chinese-Iron.png'
import Outreach from '../assets/NHI-Outreach.png'

const nhi = () => {
  return (
    <div className="portfolio-container">
    <div className="back-link">
        <Link to="/" className="btn-back-main">Back to Main Page</Link>
    </div>
      <section className="project-section">
        <h2>Nano | Human Interfaces (NHI)</h2>

        <div className="project-card">
            <p>
            The Nano | Human Interfaces Presidential Initiative aims to help scientists visualize and interpret the vast 
            amounts of data generated by research.
            </p>
            <a href="https://nhi.lehigh.edu">View the Site</a>
        </div>

        <div className="project-card">
          <p>
            <span className="subtitle">Tech-stack Used:</span>
            <ul className="tech-list">
              <li>Unity (C#, XR Interaction Toolkit)</li>
              <li>Blender</li>
              <li>Git, GitHub</li>
              <li>Adobe Aero</li>
              <li>HTC ViVE</li>
              <li>Apple Vision Pro</li>
              <li>Magic Leap</li>
              <li>HoloLens 2</li>
            </ul>
          </p>
        </div>

        <div className="project-card">
          <p className="subtitle">
            Contributions:
          </p>
          <ul className='tech-list'>
            <li>Volvox Cell AR Visualization</li>
            <li>Ni6W6C Atom Structure AR Visualization</li>
            <li>WC Atom Structure AR Visualization</li>
            <li>Microscope FIB VR OnBoarding Tutorial</li>
            <li>Microscope TEM VR OnBoarding Tutorial</li>
            <li>Chinese Artifact AR (AR Museum Proof of Concept)</li>
            <li>Chinese Arch AR (AR Museum Proof of Concept)</li>
          </ul>
        </div>

        <div className="project-card">
          <p className="subtitle">Outreach:</p>
          <img src={Outreach} alt="NHI Outreach" className="project-image" />
          <p>NHI also participates in outreach events, such as Lehigh's CHOICES, introducing technology to Technical Entrepeneruship, Mechanical
            Engineering, and Chinese classes at Lehigh, and showcases to local middle schools. We also work with local startups and institutions,
            such as Medivis, Wacker Chemicals, and ArtsQuest.</p>
          <a href="https://nhi.lehigh.edu/nhi-news">See More</a>
        </div>

        <div className="project-card">
          <p className="subtitle">(Immediately)Viewable Works</p>
          <p>Adobe Aero AR Codes, these work on any device that can scan QR codes!</p>
          <p className="subtitle">Volvox Cell</p>
          <img src={Volvox} alt="Volvox Aero QR Code" className="project-image" />
          <p className="subtitle">Ni6W6C Structure Viewer</p>
          <img src={NCW} alt="Ni6W6C Aero QR Code" className="project-image" />
          <p className="subtitle">Chinese Main Arc Artifact Viewer</p>
          <img src={ArcMain} alt="Chinese Main Arc Aero QR Code" className="project-image" />
          <p className="subtitle">Chinese Iron Arc Artifact Viewer</p>
          <img src={ChineseIron} alt="Chinese Iron Arc Aero QR Code" className="project-image" />
          <p>(Other works are available for viewing at Lehigh's NHI Lab space)</p>
        </div>
      </section>
    </div>
  );
};

export default nhi;
