import React from 'react';
import { Link } from 'react-router-dom';
import './NHI.css';

const nhi = () => {
  return (
    <div className="portfolio-container">
    <div className="back-link">
        <Link to="/" className="btn-back-main">Back to Main Page</Link>
    </div>
      <section className="project-section">
        <h2>Nano | Human Interfaces (NHI)</h2>

        <div className="project-card">
            <p>
            The Nano | Human Interfaces Presidential Initiative aims to help scientists visualize and interpret the vast 
            amounts of data generated by research.
            </p>
            <a href="https://nhi.lehigh.edu">View the Site</a>
        </div>
      </section>
    </div>
  );
};

export default nhi;
